project/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("main/", include("main.urls")),
    path("", include("food.urls")),
    # path("food/", include(("food.urls", "food"), namespace="food")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/food/urls.py
from django.urls import path

from .views import (
    IngredientItemView,
    IngredientItemAddView,
    MainView,
    RecipeView,
    RecipeAddView,
    CookView,
    CookAddView,
    CookListView,
    RecipeListView
)

urlpatterns = [
    path("", MainView.as_view(), name="main"),
    path("ingredient_item/", IngredientItemView.as_view(), name="ingredient_item"),
    path("ingredient_item_add/", IngredientItemAddView.as_view(), name="ingredient_item_add"),
    path("recipe/", RecipeView.as_view(), name="recipe"),
    path("recipe_list/", RecipeListView.as_view(), name="recipe_list"),
    path("recipe_add/", RecipeAddView.as_view(), name="recipe_add"),
    path("cook/", CookView.as_view(), name="cook"),
    path("cook_list/", CookListView.as_view(), name="cook_list"),
    path("cook_add/", CookAddView.as_view(), name="cook_add"),
]

project/main/urls.py
from django.urls import path

from .views import (
    RegisterView, LoginView, LogoutView, ProfileView,
    ProfileSettingsView, ProfileSettingsApplyView, EatCookView,
    EatCookAddView, EatIngredientView, EatIngredientAddView
)

urlpatterns = [
    path("", ProfileView.as_view(), name="profile"),
    path("profile_settings/", ProfileSettingsView.as_view(), name="profile_settings"),
    path("profile_settings_apply/", ProfileSettingsApplyView.as_view(), name="profile_settings_apply"),
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("eat_cook/", EatCookView.as_view(), name="eat_cook"),
    path("eat_cook_add/", EatCookAddView.as_view(), name="eat_cook_add"),
    path("eat_ingredient_item/", EatIngredientView.as_view(), name="eat_ingredient_item"),
    path("eat_ingredient_item_add/", EatIngredientAddView.as_view(), name="eat_ingredient_item_add"),
]

project/main/models.py
from datetime import datetime

from django.contrib.auth.models import User
from django.db import models
from django.conf import settings

from .service.other import get_path_for_avatar


class Profile(models.Model):
    """Профиль"""

    user = models.OneToOneField(User, verbose_name="Объект пользователя", on_delete=models.CASCADE)
    avatar = models.ImageField(verbose_name="Аватарка", upload_to=get_path_for_avatar, blank=True)
    calories_limit = models.PositiveSmallIntegerField("Лимит калорий в день", default=0, blank=True)
    calories_now = models.PositiveSmallIntegerField("Сколько употреблено на сегодня", default=0, blank=True)

    def get_avatar(self):
        """Возвращает ссылку на аватарку, если она не указана, вернется анонимный аватар"""
        if not self.avatar:
            return settings.ANONYMOUS_AVATAR_URL
        return self.avatar.url

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = "Профиль"
        verbose_name_plural = "Профили"


class Eating(models.Model):

    class Meta:
        abstract = True

    date = models.DateTimeField("Когда употреблено", default=datetime.now)
    count_eat = models.PositiveSmallIntegerField("Сколько грамм употреблено")
    calories_eat = models.PositiveSmallIntegerField("Сколько калорий употреблено", default=0, blank=True)


class EatCook(Eating):
    """Употребляемое блюдо"""

    cook = models.ForeignKey("food.Cook", verbose_name="Блюдо", on_delete=models.CASCADE)
    profile = models.ForeignKey(Profile, verbose_name="Профиль", on_delete=models.CASCADE,
                                related_name="related_eat_cooks")

    def __str__(self):
        return f"{self.cook.recipe.title} - {self.profile.user.username}"

    class Meta:
        verbose_name = "Употребленное блюдо"
        verbose_name_plural = "Употребленное блюда"


class EatIngredient(Eating):
    """Употребляемый ингредиент"""

    ingredient_item = models.ForeignKey("food.IngredientItem", verbose_name="Продукт", on_delete=models.CASCADE)
    profile = models.ForeignKey(Profile, verbose_name="Профиль", on_delete=models.CASCADE,
                                related_name="related_eat_ingredient")

    def __str__(self):
        return f"Употребление продукта {self.ingredient_item.ingredient.title}"

    class Meta:
        verbose_name = "Употребленный продукт"
        verbose_name_plural = "Употребленные продукты"

project/main/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User

from .models import Profile, EatCook, EatIngredient
from .service.models import create_model_profile

from food.service.models import get_model_cook__already, get_model_ingredient_item__already


class RegisterUserForm(forms.ModelForm):
    """Форма регистрации"""

    class Meta:
        model = User
        fields = ("username", "password")
        widgets = {
            "password": forms.TextInput(attrs={"type": "password"})
        }

    def __init__(self, *args, **kwargs):
        """Изменение поведение формы при инициализации. Добавляем в поля формы класс form-class"""
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = "form-class"

    def save(self, commit=True):
        """Изменение поведение формы при сохранении. Добавляем User и создаем пустой профиль"""
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        create_model_profile(user)
        return user


# AuthenticationForm Для проверки, пользователь авторизован, существует пользователь в системе или нет и тд
class LoginForm(AuthenticationForm, forms.ModelForm):
    """Форма авторизации"""

    class Meta:
        model = User
        fields = ("username", "password")


class ProfileSettingsForm(forms.ModelForm):
    """Форма для изменение данных профиля"""

    class Meta:
        model = Profile
        fields = ("calories_limit",)


class EatCookForm(forms.ModelForm):
    """Форма употребляемого блюда"""

    cook = forms.ModelChoiceField(
        queryset=get_model_cook__already(), widget=forms.Select(), empty_label="---------", label="Блюдо"
    )

    class Meta:
        model = EatCook
        fields = ("cook", "count_eat", "date")
        widgets = {
            "date": forms.DateTimeInput(attrs={"type": "datetime-local", "help_text": "Hello"})
        }
        help_texts = {
            "date": "Поумолчанию текущее время"
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['date'].required = False


class EatIngredientForm(forms.ModelForm):
    """Форма употребляемого ингредиента"""

    ingredient_item = forms.ModelChoiceField(
        queryset=get_model_ingredient_item__already(), widget=forms.Select(), empty_label="---------", label="Продукт"
    )

    class Meta:
        model = EatIngredient
        fields = ("ingredient_item", "count_eat", 'date')
        widgets = {
            "date": forms.DateTimeInput(attrs={"type": "datetime-local", "required": False}, )
        }
        help_texts = {
            "date": "Поумолчанию текущее время"
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['date'].required = False

project/main/service/views.py
from datetime import datetime

from django.contrib import messages as django_messages

from .essential import add_model_profile_to__calories_now, check_have_username
from .models import (
    get_eat_cook__today,
    get_profile_by__user,
    create_model_eat
)
from food.service.models import get_model_cook_by__id, get_model_ingredient_item_by__id
from food.service.essential import change_cook__now_weight, change_ingredient_item__count_now


def set_info_for_profile_in_context(context, user):
    """"""
    profile = get_profile_by__user(user)
    eat_cooks = get_eat_cook__today(profile)
    # print(eat_cooks)


def message_manager(request, result: dict) -> None:
    """Отрпавляет пришедшие сообщение на сайт"""
    message_tag = django_messages.INFO
    if not result['success']:
        message_tag = django_messages.ERROR
    for message in result['messages']:
        django_messages.add_message(request, message_tag, message)


def change_profile(request: dict) -> dict:
    """
        Применяет настройки профиля
        - Изменяет аватарку
        - Изменяет ник
        - Изменяет лимит калорий в день
        Возвращает результат применения настроек с сообщениями
    """
    success = True
    messages = []

    # Начальные данные
    data = request.POST
    files = request.FILES
    user = request.user
    profile = get_profile_by__user(user)

    avatar = files.get("avatar")
    username = data.get("username")
    calories_limit = data.get("calories_limit")

    # Если передали аватар
    if avatar:
        ext = avatar.name.split(".")[1]
        if ext == "jpg" or ext == "png":
            profile.avatar = avatar
        else:
            messages.append("Приложение не принимает картинки формата {}".format(ext))
            success = False

    # Если передали ник
    if username != user.username and success:
        if not check_have_username(username):
            messages.append(f"Изменили ник с {user.username} на {username}")
            user.username = username
        else:
            messages.append("Пользователь с таким ником существует")
            success = False

    # Если передали лимит калорий
    if calories_limit != profile.calories_limit and success:
        messages.append(f"Изменили лимит калорий с {profile.calories_limit} на {calories_limit}")
        profile.calories_limit = calories_limit

    # Сохраняем
    if success:
        user.save()
        profile.save()

    return {"success": success, "messages": messages}


def create_eat_cook(request: dict) -> dict:
    """
        Создает EatCook
        Возвращает результат создания с сообщениями
    """
    success = True
    messages = []

    # Начальные данные
    data = request.POST
    user = request.user
    profile = get_profile_by__user(user)
    cook = get_model_cook_by__id(data['cook'])

    date = data['date']
    count_eat = int(data['count_eat'])

    # Высчитываем сколько каллорий употреблено
    calories_eat = int((count_eat/100) * cook.total_calories)

    # Создаем EatCook
    if cook.now_weight >= count_eat:
        create_model_eat(cook, profile, count_eat, calories_eat, date=date)
    else:
        success = False
        messages.append("Вы ввели больше чем есть. Блюда осталось {} грамм".format(cook.now_weight))

    if success:
        # Меняем в профиле количество калорий на текущий день
        add_model_profile_to__calories_now(profile, calories_eat)

        # Меняем количество блюда
        change_cook__now_weight(cook, count_eat)

        messages.append(f"Добавили употребление блюда {cook} в размере {count_eat}г")
    return {"success": success, "messages": messages}


def create_eat_ingredient(request: dict) -> dict:
    """Создает EatIngredient
    Возвращает результат создания с сообщениями"""
    success = True
    messages = []

    # Начальные данные
    data = request.POST
    user = request.user
    profile = get_profile_by__user(user)
    ingredient_item = get_model_ingredient_item_by__id(data['ingredient_item'])

    date = data['date']
    count_eat = int(data['count_eat'])

    # Высчитываем сколько каллорий употреблено
    calories_eat = int((count_eat / 100) * ingredient_item.ingredient.calories)

    # Создаем EatCook
    if ingredient_item.count_now >= count_eat:
        create_model_eat(ingredient_item, profile, count_eat, calories_eat, date=date)
    else:
        success = False
        messages.append("Вы ввели больше чем есть. Ингредиента осталось {} грамм".format(ingredient_item.count_now))

    if success:
        # Меняем в профиле количество калорий на текущий день
        add_model_profile_to__calories_now(profile, calories_eat)

        # Меняем количество блюда
        change_ingredient_item__count_now(ingredient_item, count_eat)

        messages.append(f"Добавили употребление блюда {ingredient_item.ingredient.title} в размере {count_eat}г")
    return {"success": success, "messages": messages}

project/main/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView as LoginViewParent, LogoutView as LogoutViewParent
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView

from .forms import RegisterUserForm, LoginForm, ProfileSettingsForm, EatIngredientForm
from .models import Profile

from config.service.views import set_model_get_in_context, set_model_all_in_context, set_model_filter_in_context

from .forms import EatCookForm
from .service.essential import update_profile
from .service.views import set_info_for_profile_in_context, change_profile, create_eat_cook, message_manager, \
    create_eat_ingredient
from food.models import Cook, IngredientItem


class LoginView(LoginViewParent):
    """Показывает страницу с Авторизацией"""
    template_name = "login_page.html"
    form_class = LoginForm
    success_url = reverse_lazy("main")

    def get_success_url(self):  # переопределям
        return self.success_url


class RegisterView(CreateView):
    """Показывает страницу с Регистрацией"""

    model = User
    template_name = "register_page.html"
    form_class = RegisterUserForm
    success_url = reverse_lazy("main")

    def form_valid(self, form):
        """Правильно сохранение пароля в django"""
        form_valid = super().form_valid(form)
        username = form.cleaned_data["username"]
        password = form.cleaned_data["password"]
        aut_user = authenticate(username=username, password=password)
        login(self.request, aut_user)
        return form_valid


class LogoutView(LogoutViewParent):
    """Выход из аккаунта"""
    next_page = reverse_lazy('main')


class ProfileView(View):
    """Показывает страницу профиля"""

    def get(self, request, *args, **kwargs):
        context = dict()
        update_profile(request.user)
        set_model_get_in_context(Profile, context, user=request.user)
        set_info_for_profile_in_context(context, request.user)
        return render(request, "profile_page.html", context=context)


class ProfileSettingsView(View):
    """Показывает страницу настроек профиля"""

    def get(self, request, *args, **kwargs):
        context = dict()
        return render(request, "profile_settings.html", context=context)


class ProfileSettingsApplyView(View):
    """Принятие настроек пользователя"""

    def post(self, request, *args, **kwargs):
        result = change_profile(request)
        message_manager(request, result)
        if not result["success"]:
            return redirect("/main/profile_settings")
        return redirect("/main")


class EatCookView(View):
    """Показывает страницу употребления блюда"""

    def get(self, request, *args, **kwargs):
        form = EatCookForm()
        context = dict()
        context["form"] = form
        set_model_filter_in_context(Cook, context, is_ended=False, is_overdue=False)
        return render(request, "eat_cook.html", context=context)


class EatCookAddView(View):
    """Принимает post запрос, для добавления употребляемого блюда"""

    def post(self, request, *args, **kwargs):
        result = create_eat_cook(request)
        message_manager(request, result)
        return redirect("/main/eat_cook")


class EatIngredientView(View):
    """Показывает страницу употребления продукта"""

    def get(self, request, *args, **kwargs):
        form = EatIngredientForm()
        context = dict()
        context["form"] = form
        set_model_filter_in_context(IngredientItem, context, name_field="ingredient_items",
                                    is_ended=False, is_overdue=False)
        return render(request, "eat_ingredient_item.html", context=context)


class EatIngredientAddView(View):
    """Принимает post запрос, для добавления употребляемого продукта"""

    def post(self, request, *args, **kwargs):
        result = create_eat_ingredient(request)
        message_manager(request, result)
        return redirect("/main/eat_ingredient_item")

project/main/templates/eat_cook.html
{% extends 'base.html' %}
{% block title %}Страница употребления блюда{% endblock title %}
{% block page_name %}Страница употребления блюда{% endblock page_name %}

{% block content %}
<form method="post" action="{% url 'eat_cook_add' %}">
    {% csrf_token %}
    <label for="id_cook">Блюдо</label>
    {{ form.cook }}
    <br>
    <label for="id_count_eat">Сколько употребили</label>
    {{ form.count_eat }}
    <label for="id_count_eat"  id="show_count">Имеется в наличии</label><br>
    {{ form.date }}
    {{ form.date.help_text }}<br>
    <button id="get_all">Употребить все</button>
    <button type="submit">Записать</button>
</form>

<script>
    const cook_choice = document.getElementById("id_cook")
    const count_eat = document.getElementById("id_count_eat")
    const get_all = document.getElementById("get_all")
    const show_count = document.getElementById("show_count")

    let objects = {}

    {% for cook in cooks %}
        objects["cook_{{ cook.id }}"] = {{ cook.now_weight }}
    {% endfor %}


    get_all.addEventListener("click", function(event){
        choice = cook_choice.value
        count_eat.value = objects["cook_"+choice]
    });

    cook_choice.addEventListener("click", function(event){
        choice = cook_choice.value
        show_count.innerHTML = "Имеется в наличии: "
        if (objects["cook_"+choice])
            show_count.innerHTML += objects["cook_"+choice]

    });



</script>

{% endblock content %}

project/main/templates/eat_ingredient_item.html
{% extends 'base.html' %}
{% block title %}Страница употребления ингредиента{% endblock title %}
{% block page_name %}Страница употребления ингредиента{% endblock page_name %}

{% block content %}
<form method="post" action="{% url 'eat_ingredient_item_add' %}">
    {% csrf_token %}
    <label for="id_cook">Продукт</label>
    {{ form.ingredient_item }}
    <br>
    <label for="id_count_eat">Сколько употребили</label>
    {{ form.count_eat }}
    <label for="id_count_eat" id="show_count">Имеется в наличии</label><br>
    {{ form.date }}
    {{ form.date.help_text }}<br>
    <button id="get_all">Употребить все</button>
    <button type="submit">Записать</button>
</form>


{% for cook in cooks %}
    {{ cook.now_weight }}
{% endfor %}


<script>
    const ingredient_item = document.getElementById("id_ingredient_item")
    const count_eat = document.getElementById("id_count_eat")
    const get_all = document.getElementById("get_all")
    const show_count = document.getElementById("show_count")

    let objects = {}

    {% for ingredient_item in ingredient_items %}
        objects["ingredient_item_{{ ingredient_item.id }}"] = {{ ingredient_item.count_now }}
    {% endfor %}


    get_all.addEventListener("click", function(event){
        choice = ingredient_item.value
        count_eat.value = objects["ingredient_item_"+choice]
    });

    ingredient_item.addEventListener("click", function(event){
        choice = ingredient_item.value
        show_count.innerHTML = "Имеется в наличии: "
        if (objects["ingredient_item_"+choice])
            show_count.innerHTML += objects["ingredient_item_"+choice]

    });


</script>

{% endblock content %}

project/main/templates/login_page.html
{% extends 'base.html' %}
{% block title %}Страница регистрации{% endblock title %}
{% block page_name %}Страница регистрации{% endblock page_name %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_ul }}
    <button type="submit">Залогиниться</button>
</form>

{% endblock content %}

project/main/templates/main_main.html
{% extends 'base.html' %}
{% block title %}Главная страница{% endblock title %}
{% block page_name %}Главная страница{% endblock page_name %}

{% block content %}
hello
{% endblock content %}

project/main/templates/profile_page.html
{% extends 'base.html' %}
{% load eat_items %}

{% block title %}Профиль{% endblock title %}
{% block page_name %}
Профиль
<div class="auth"><span><a href="{% url 'profile_settings' %}">Настройки</a></span></div>
{% endblock page_name %}

{% block content %}

<div class="profile">
    <div class="profile_image-block">
        <img src="{{ profile.get_avatar }}" alt="Аватарка">
    </div>
    <div class="profile_info">
        <span>Ник: {{ profile.user.username }}</span>
        <span>Каллории {{ profile.calories_now }}/{{ profile.calories_limit }}</span>
    </div>
</div>


{% get_eats user=request.user %}

{% endblock content %}

project/main/templates/profile_settings.html
{% extends 'base.html' %}
{% block title %}Профиль{% endblock title %}
{% block page_name %}
Профиль
<div class="auth"><span>Настройки</span></div>
{% endblock page_name %}

{% block content %}

<form action="{% url 'profile_settings_apply' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="profile">
        <div class="profile_image-block">
            <img src="{{ user.profile.get_avatar }}" alt="Аватарка">
            <label for="id_avatar">Изменить аватар</label>
            <input type="file" name="avatar" id="id_avatar">
        </div>
        <div class="profile_info">
            <label for="id_username">Изменить ник</label>
            <input type="text" name="username" id="id_username" value="{{ user.username }}">
            <label for="id_calories_limit">Изменить лимит калорий</label>
            <input type="text" name="calories_limit" id="id_calories_limit" value="{{ user.profile.calories_limit }}">
        </div>
        <button type="submit">Сохранить</button>
    </div>
</form>
{% endblock content %}

project/main/templates/register_page.html
{% extends 'base.html' %}
{% block title %}Страница регистрации{% endblock title %}
{% block page_name %}Страница регистрации{% endblock page_name %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_ul }}
    <button type="submit">Зарегистрироваться</button>
</form>

{% endblock content %}